### ISSUE TITLE
Can't link with NDK r12 libc++

### ISSUE THREAD

**Issue by ringoz** [playgameservices/cpp-android-basic-samples#39]
Using latest Android NDK r12 one can't build the samples.

APP_STL := c++_static
NDK_TOOLCHAIN_VERSION := clang

There are a bunch of linking errors when using libc++.
For example: 
`libgpg.a:all.cc:function gpg::StateMachine::~StateMachine(): error: undefined reference to 'std::__1::recursive_mutex::~recursive_mutex()'`

**Comment by ggfan** [comment]
thank you for filing the bug, will have a look: in general, it is kind of trouble using different ndk version to build your gpg game from the one they used to build libgpg.a, specifically for the problem like this kind.

I am not sure which ndk version they were using to build gpg lib you are linking with, certainly not 12. and there are changes between 11 ( I am not sure libgpg.a is built with 10 or 11 ) and 12...

**Comment by claywilkinson** [comment]
The Play Game Services SDK requires r10.

**Comment by Jakz** [comment]
How are we supposed to solve this issue? I'm working on Android Studio 2.2.2 with NDK r13 and I'd like to use libgpg but I'm unable to link the final native library for the given link errors, unable to find references to std library function implementations (I'm working with clang and c++_static)

**Comment by ggfan** [comment]
Yeah, not now.  Once play service team release their built with ndk-r12, android studio 2.2.0+ could be used.  Gradle-experimental is the only choice before they release new google play games services.

**Comment by claywilkinson** [comment]
You can change the NDK used in your Android Studio project by editing the local.settings file in your Android Studio project.  As mentioned earlier, you need to use r10e when using the GPGS C++ SDK.  

You can use the ndkbuild option within Android Studio to build with r10e.
